<a href="https://colab.research.google.com/github/Dhanavijayan/ML_OPS_Tasks/blob/main/Train%26Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

file_path = "supermarket_sample.csv"
df = pd.read_csv(file_path)
df.head()

,Row_ID,Foot_Traffic,Staff_Count,Hour,High_Value_Items,Shrinkage_INR,Predicted_INR,Residual_INR,Theft_Level
0,1,164,3,16,30,293,330,-37,Low
1,2,62,6,10,89,322,174,148,Low
2,3,434,6,16,88,870,841,29,High
3,4,91,3,20,93,593,476,117,Medium
4,5,298,3,15,33,712,579,133,High

In [2]:
X = df[["Foot_Traffic", "Hour"]]
y = df["Shrinkage_INR"]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [4]:
X_test

     Foot_Traffic  Hour
201           180    13
348           493    18
164           490    20
455           267    20
446           143    11
..            ...   ...
448           475     9
436           334    18
464           390    19
233           278     9
203           232     9

[150 rows x 2 columns]

In [5]:
y_test

201     338
348    1008
164     957
455     513
446     399
       ...
448     849
436     922
464     664
233     382
203     564
Name: Shrinkage_INR, Length: 150, dtype: int64

In [6]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [7]:
clf.predict(X_test)

array([328.87030279, 915.31053702, 929.94038264, 547.35057516,
       245.61448273, 286.88371951, 892.10244459, 616.600244  ,
       507.79698775, 168.8157608 , 660.17793367, 820.45067075,
       626.27044576, 621.34169277, 445.12896002, 465.62310024,
       778.55773957, 367.83108667, 895.128244  , 821.26166937,
       214.23364281, 378.71778637, 736.07200486, 618.00404616,
       536.55752757, 874.04130025, 658.77413151,  71.42924654,
       365.70993799, 438.57820978, 665.94857615, 902.39634076,
       618.00404616, 742.34179877, 819.04686859, 241.27853327,
       901.58534213, 174.55551242, 591.36465501, 572.67981626,
       424.44751558, 375.50468274, 420.20521823, 594.48410653,
       824.38112089, 848.30655983, 336.94939817, 776.84209021,
       428.37796572, 815.61556986, 493.75994566, 140.5543724 ,
       473.57765264, 483.18509316, 715.20325619, 382.05543298,
       189.80905245, 677.95812168, 307.78335904, 183.13375923,
       159.9256668 , 779.6805854 , 152.25207073, 379.84063219,
       228.86348844, 396.3734314 , 805.50897792, 437.14351675,
       641.11848648, 343.59380053, 457.54400486, 170.12591085,
       462.78460505, 333.70540367, 561.29396514, 301.41991302,
       340.47434901, 804.01152365, 684.41521981, 773.22348727,
       566.94006464, 709.93176514, 537.27487409, 160.64301331,
       615.78924537, 633.3512383 , 104.52573583, 519.61922905,
       478.63094861, 602.96870122, 526.76278283, 356.9134961 ,
       855.9801559 , 317.4535608 , 163.66881272, 429.78176788,
       456.82665835,  84.74894212, 497.40943947, 339.56969827,
       317.35990869, 634.66138834, 775.93743947, 448.15475943,
       536.77572266, 529.1957787 , 383.05373583, 218.56959227,
       186.37775372, 149.53811852, 830.83821902, 749.39170044,
       725.09165305, 362.68413859, 827.7187675 , 237.94088666,
       364.08794075, 301.41991302, 819.63967212, 517.18623318,
       424.22932049, 143.58017181, 862.53090614, 236.72438873,
       826.50226956, 872.01380368, 494.78913937, 690.56047074,
       571.36966621, 785.82583633, 542.60912639, 470.77004832,
       137.62222511, 207.87019679, 681.88857183, 527.79197654,
       306.97236041, 296.36661705, 701.25986622, 593.17395648,
       613.9799439 , 922.17313446, 544.94847015, 274.06317535,
       148.7271199 , 795.43327685, 642.52228864, 748.4870497 ,
       457.45035275, 378.53048215])

In [8]:
clf.score(X_test, y_test)

0.755082428158032

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
X_test

     Foot_Traffic  Hour
151           355    16
424           320     8
154           493    14
190           429    14
131           374    17
..            ...   ...
12            202    10
97            201    19
130           327    11
472           300    11
315           355     9

[150 rows x 2 columns]